//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window.Dialog {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.Dialog.ConfigRes", typeof(ConfigRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 アクセスキー： 的本地化字符串。
        /// </summary>
        public static string AccessKey {
            get {
                return ResourceManager.GetString("AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バージョン名をファイルに追加します。 的本地化字符串。
        /// </summary>
        public static string AddVersionToFile {
            get {
                return ResourceManager.GetString("AddVersionToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空戦力計算式： 的本地化字符串。
        /// </summary>
        public static string AirSuperiorityMethod {
            get {
                return ResourceManager.GetString("AirSuperiorityMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー音を鳴らす 的本地化字符串。
        /// </summary>
        public static string AlertOnError {
            get {
                return ResourceManager.GetString("AlertOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ソート順を変更可能にする 的本地化字符串。
        /// </summary>
        public static string AllowUserToSortRows {
            get {
                return ResourceManager.GetString("AllowUserToSortRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泊地修理 的本地化字符串。
        /// </summary>
        public static string AnchorageRepairFinish {
            get {
                return ResourceManager.GetString("AnchorageRepairFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 適用 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在のテキストボックスの内容を適用します。 的本地化字符串。
        /// </summary>
        public static string ApplyEffectsOfBox {
            get {
                return ResourceManager.GetString("ApplyEffectsOfBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリに登録します。よろしいですか？
        ///＊完全に適用するには再起動が必要です。 的本地化字符串。
        /// </summary>
        public static string ApplyingRegistry {
            get {
                return ResourceManager.GetString("ApplyingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＊各ダイアログでOKを押した時点で適用されます 的本地化字符串。
        /// </summary>
        public static string ApplyonOK {
            get {
                return ResourceManager.GetString("ApplyonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 適用 的本地化字符串。
        /// </summary>
        public static string ApplyRegistry {
            get {
                return ResourceManager.GetString("ApplyRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリに対して設定を適用します。
        ///下の[OK]ボタンでは反映されないのでご注意ください。 的本地化字符串。
        /// </summary>
        public static string ApplyRegistryHint {
            get {
                return ResourceManager.GetString("ApplyRegistryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スタイルシートを適用する 的本地化字符串。
        /// </summary>
        public static string ApplyStyleSheet {
            get {
                return ResourceManager.GetString("ApplyStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これ画面のみを表示できるようにします。
        ///環境によっては表示が乱れます、その場合は無効にしてください。 的本地化字符串。
        /// </summary>
        public static string ApplyStyleSheetHint {
            get {
                return ResourceManager.GetString("ApplyStyleSheetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工廠 的本地化字符串。
        /// </summary>
        public static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動更新する 的本地化字符串。
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船データを自動更新するかを指定します。 的本地化字符串。
        /// </summary>
        public static string AutoUpdateHint {
            get {
                return ResourceManager.GetString("AutoUpdateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2-5式(秋) 的本地化字符串。
        /// </summary>
        public static string Autumn25 {
            get {
                return ResourceManager.GetString("Autumn25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 動作 的本地化字符串。
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BGMプレイヤーを有効にする 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_Enabled {
            get {
                return ResourceManager.GetString("BGMPlayer_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在の場面に合わせてお好みのBGMを再生する機能です。 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_Enabled_Tooltip {
            get {
                return ResourceManager.GetString("BGMPlayer_Enabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音楽ファイルを開く 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_OpenMusicFile {
            get {
                return ResourceManager.GetString("BGMPlayer_OpenMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BGMの設定 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_Settings {
            get {
                return ResourceManager.GetString("BGMPlayer_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量一括適用 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_SetVolumeAll {
            get {
                return ResourceManager.GetString("BGMPlayer_SetVolumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ミュートを同期 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_SyncBrowserMute {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザのミュートと連動させるかを指定します。 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_SyncBrowserMute_Tooltip {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完了時に点滅させる 的本地化字符串。
        /// </summary>
        public static string BlinkAtCompletion {
            get {
                return ResourceManager.GetString("BlinkAtCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船/装備が満タンの時点滅する 的本地化字符串。
        /// </summary>
        public static string BlinkAtMaximum {
            get {
                return ResourceManager.GetString("BlinkAtMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザフォント.
        /// </summary>
        public static string BrowserFont {
            get {
                return ResourceManager.GetString("BrowserFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザバージョン：.
        /// </summary>
        public static string BrowserVersion {
            get {
                return ResourceManager.GetString("BrowserVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内蔵ブラウザのバージョンを指定します。
        ///7000がIE7相当、8000がIE8相当、11000がIE11相当です。
        ///バージョンによって動作が変わる可能性があります。 的本地化字符串。
        /// </summary>
        public static string BrowserVersionHint {
            get {
                return ResourceManager.GetString("BrowserVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャンセル 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一度に表示する候補数： 的本地化字符串。
        /// </summary>
        public static string CandidateDisplayCount {
            get {
                return ResourceManager.GetString("CandidateDisplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリを削除します。よろしいですか？
        ///＊完全に適用するには再起動が必要です。 的本地化字符串。
        /// </summary>
        public static string ClearingRegistry {
            get {
                return ResourceManager.GetString("ClearingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信 的本地化字符串。
        /// </summary>
        public static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一度に表示する候補数： 的本地化字符串。
        /// </summary>
        public static string CompassCandidate {
            get {
                return ResourceManager.GetString("CompassCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合再読み込みするときに確認ダイアログを表示します。
        ///誤爆防止にご利用ください。 的本地化字符串。
        /// </summary>
        public static string ConfirmRefreshHint {
            get {
                return ResourceManager.GetString("ConfirmRefreshHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポート番号を設定します。 的本地化字符串。
        /// </summary>
        public static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了 的本地化字符串。
        /// </summary>
        public static string ConstructEnd {
            get {
                return ResourceManager.GetString("ConstructEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＊無闇に変更すると設定・レコードが読めなくなる可能性があります 的本地化字符串。
        /// </summary>
        public static string CorruptLogs {
            get {
                return ResourceManager.GetString("CorruptLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作成完了 的本地化字符串。
        /// </summary>
        public static string CreationComplete {
            get {
                return ResourceManager.GetString("CreationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デイリー 的本地化字符串。
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データベース 的本地化字符串。
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「艦これ統計データベース」へデータを送信できます。
        ///詳細やアクセスキーの取得は以下のサイトを参照してください。(外部ブラウザが開きます) 的本地化字符串。
        /// </summary>
        public static string DatabaseDescription {
            get {
                return ResourceManager.GetString("DatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デバッグ 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除 的本地化字符串。
        /// </summary>
        public static string DeleteRegistry {
            get {
                return ResourceManager.GetString("DeleteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリを削除します。 的本地化字符串。
        /// </summary>
        public static string DeleteRegistryHint {
            get {
                return ResourceManager.GetString("DeleteRegistryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修レベル・熟練度を表示する 的本地化字符串。
        /// </summary>
        public static string DisplayEquipLevels {
            get {
                return ResourceManager.GetString("DisplayEquipLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備の改修レベルと艦載機熟練度を表示するかを指定します。
        /// 的本地化字符串。
        /// </summary>
        public static string DisplayEquipLevelsTooltip {
            get {
                return ResourceManager.GetString("DisplayEquipLevelsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠 的本地化字符串。
        /// </summary>
        public static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠完了 的本地化字符串。
        /// </summary>
        public static string DockEnd {
            get {
                return ResourceManager.GetString("DockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時に読み込む 的本地化字符串。
        /// </summary>
        public static string EnableBrowser {
            get {
                return ResourceManager.GetString("EnableBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ローカル キャッシュを利用 的本地化字符串。
        /// </summary>
        public static string EnableLocalCache {
            get {
                return ResourceManager.GetString("EnableLocalCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入出力するファイルのエンコーディングを指定します。
        ///＊注意＊変更すると今までの設定やレコードが読み込めなくなる可能性があります。
        ///十分注意して変更してください。 的本地化字符串。
        /// </summary>
        public static string EncodingHint {
            get {
                return ResourceManager.GetString("EncodingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字コード 的本地化字符串。
        /// </summary>
        public static string Enocding {
            get {
                return ResourceManager.GetString("Enocding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 両方表示 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_Both {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非表示 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_Hidden {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修レベルのみ 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_ImprovOnly {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ImprovOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修レベル優先 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_ImprovPrio {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ImprovPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦載機熟練度のみ 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_ProfOnly {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ProfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦載機熟練度優先 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_ProfPrio {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ProfPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征帰投 的本地化字符串。
        /// </summary>
        public static string ExpedReturn {
            get {
                return ResourceManager.GetString("ExpedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリの削除に失敗しました。 的本地化字符串。
        /// </summary>
        public static string FailedClearRegistry {
            get {
                return ResourceManager.GetString("FailedClearRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリからの読み込みに失敗しました。 的本地化字符串。
        /// </summary>
        public static string FailedLoadRegistry {
            get {
                return ResourceManager.GetString("FailedLoadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトの保存に失敗しました。 的本地化字符串。
        /// </summary>
        public static string FailedSaveProxy {
            get {
                return ResourceManager.GetString("FailedSaveProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリへの書き込みに失敗しました。 的本地化字符串。
        /// </summary>
        public static string FailedSaveRegistry {
            get {
                return ResourceManager.GetString("FailedSaveRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザバージョンをレジストリに書き込めませんでした。 的本地化字符串。
        /// </summary>
        public static string FailWriteRegistry {
            get {
                return ResourceManager.GetString("FailWriteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労回復 的本地化字符串。
        /// </summary>
        public static string FatigueRestore {
            get {
                return ResourceManager.GetString("FatigueRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイル名 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フィルタ 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合、画面に合わせて自動的に拡大・縮小します。 的本地化字符串。
        /// </summary>
        public static string FitHint {
            get {
                return ResourceManager.GetString("FitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flashのモードを指定します。
        ///既定値は opaque です。
        ///direct にするとパフォーマンスが向上する可能性があります。 的本地化字符串。
        /// </summary>
        public static string FlashModeHint {
            get {
                return ResourceManager.GetString("FlashModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash品質設定 的本地化字符串。
        /// </summary>
        public static string FlashQuality {
            get {
                return ResourceManager.GetString("FlashQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイマー完了時に点滅させる 的本地化字符串。
        /// </summary>
        public static string FleetBlinkAtCompletion {
            get {
                return ResourceManager.GetString("FleetBlinkAtCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フォルダの参照 的本地化字符串。
        /// </summary>
        public static string FolderSearch {
            get {
                return ResourceManager.GetString("FolderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判定式(33) 的本地化字符串。
        /// </summary>
        public static string Formula33 {
            get {
                return ResourceManager.GetString("Formula33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPUレンダリング 的本地化字符串。
        /// </summary>
        public static string GPURendering {
            get {
                return ResourceManager.GetString("GPURendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内蔵ブラウザでGPUレンダリングを使用するかを指定します。
        ///環境によっては処理が高速化します。 的本地化字符串。
        /// </summary>
        public static string GPURenderingHint {
            get {
                return ResourceManager.GetString("GPURenderingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 グループ 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (非表示です。デバッグメニューを有効にしてください。) 的本地化字符串。
        /// </summary>
        public static string HiddenJSON {
            get {
                return ResourceManager.GetString("HiddenJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウトファイル 的本地化字符串。
        /// </summary>
        public static string LayoutFile {
            get {
                return ResourceManager.GetString("LayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウト ファイルを開く 的本地化字符串。
        /// </summary>
        public static string LayoutSearch {
            get {
                return ResourceManager.GetString("LayoutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先頭： 的本地化字符串。
        /// </summary>
        public static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロック中でもフロートウィンドウを閉じる 的本地化字符串。
        /// </summary>
        public static string Life_CanCloseFloatWindowInLock {
            get {
                return ResourceManager.GetString("Life_CanCloseFloatWindowInLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログ 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レコードの自動保存： 的本地化字符串。
        /// </summary>
        public static string LoggingInterval {
            get {
                return ResourceManager.GetString("LoggingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログの出力レベル 的本地化字符串。
        /// </summary>
        public static string LoggingLevel {
            get {
                return ResourceManager.GetString("LoggingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログインURL 的本地化字符串。
        /// </summary>
        public static string LoginURL {
            get {
                return ResourceManager.GetString("LoginURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ループ 的本地化字符串。
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵能力計算式 的本地化字符串。
        /// </summary>
        public static string LosFormula {
            get {
                return ResourceManager.GetString("LosFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 メインフォント 的本地化字符串。
        /// </summary>
        public static string Mainfont {
            get {
                return ResourceManager.GetString("Mainfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインフォントに合わせる.
        /// </summary>
        public static string MatchMainFont {
            get {
                return ResourceManager.GetString("MatchMainFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊膨大なサイズになる可能性があります。.
        /// </summary>
        public static string MayIncreaseSize {
            get {
                return ResourceManager.GetString("MayIncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 モード 的本地化字符串。
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 マンスリー 的本地化字符串。
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労度ボーダー 的本地化字符串。
        /// </summary>
        public static string MoraleBorder {
            get {
                return ResourceManager.GetString("MoraleBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2-5新秋簡易式 的本地化字符串。
        /// </summary>
        public static string New25 {
            get {
                return ResourceManager.GetString("New25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新判定式(33) 的本地化字符串。
        /// </summary>
        public static string NewFormula33 {
            get {
                return ResourceManager.GetString("NewFormula33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知の設定... 的本地化字符串。
        /// </summary>
        public static string NotificationSetting {
            get {
                return ResourceManager.GetString("NotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (旧)2-5式 的本地化字符串。
        /// </summary>
        public static string Old25 {
            get {
                return ResourceManager.GetString("Old25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一回限り・その他 的本地化字符串。
        /// </summary>
        public static string OneTimeOther {
            get {
                return ResourceManager.GetString("OneTimeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 その他 的本地化字符串。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトの出力... 的本地化字符串。
        /// </summary>
        public static string OutputProxyScript {
            get {
                return ResourceManager.GetString("OutputProxyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 パス： 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポート 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 威力表示交戦形態： 的本地化字符串。
        /// </summary>
        public static string PowerEngagementForm {
            get {
                return ResourceManager.GetString("PowerEngagementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務進捗の自動保存： 的本地化字符串。
        /// </summary>
        public static string ProgressAutoSaving {
            get {
                return ResourceManager.GetString("ProgressAutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1日ごと 的本地化字符串。
        /// </summary>
        public static string ProgressAutoSaving_Daily {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 しない 的本地化字符串。
        /// </summary>
        public static string ProgressAutoSaving_Disable {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1時間ごと 的本地化字符串。
        /// </summary>
        public static string ProgressAutoSaving_Hourly {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存し、設定用URLをクリップボードにコピーしました。
        ///所定の位置に貼り付けてください。 的本地化字符串。
        /// </summary>
        public static string ProxyScriptSaved {
            get {
                return ResourceManager.GetString("ProxyScriptSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品質 的本地化字符串。
        /// </summary>
        public static string QualitySelect {
            get {
                return ResourceManager.GetString("QualitySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flashの品質を設定します。
        ///既定値は high です。 的本地化字符串。
        /// </summary>
        public static string QualitySelectHint {
            get {
                return ResourceManager.GetString("QualitySelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務 的本地化字符串。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レコードの自動保存： 的本地化字符串。
        /// </summary>
        public static string RecordAutoSaving {
            get {
                return ResourceManager.GetString("RecordAutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1日ごと 的本地化字符串。
        /// </summary>
        public static string RecordAutoSaving_Daily {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 しない 的本地化字符串。
        /// </summary>
        public static string RecordAutoSaving_Disable {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1時間ごと 的本地化字符串。
        /// </summary>
        public static string RecordAutoSaving_Hourly {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レジストリ 的本地化字符串。
        /// </summary>
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシをシステムに登録し、自動的に通信できるようにします。
        ///プロキシ設定が不要になりますが、副作用があるため注意してご利用ください。
        ///詳細はオンラインヘルプを参照してください。 的本地化字符串。
        /// </summary>
        public static string RegSystemProxyHint {
            get {
                return ResourceManager.GetString("RegSystemProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべての通信ファイルを保存します。 的本地化字符串。
        /// </summary>
        public static string SaveAllConnectionFiles {
            get {
                return ResourceManager.GetString("SaveAllConnectionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APIのRequest部を保存します。 的本地化字符串。
        /// </summary>
        public static string SaveAPIRequests {
            get {
                return ResourceManager.GetString("SaveAPIRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APIのResponse部を保存します。 的本地化字符串。
        /// </summary>
        public static string SaveAPIResponses {
            get {
                return ResourceManager.GetString("SaveAPIResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラーが発生した際に記録を残します。
        ///記録されたファイルを送信していただければバグ修正に役立てることができます。
        ///デフォルトでは実行フォルダ内 ErrorReport フォルダに保存されます。 的本地化字符串。
        /// </summary>
        public static string SaveErrorHint {
            get {
                return ResourceManager.GetString("SaveErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラーレポートを保存する 的本地化字符串。
        /// </summary>
        public static string SaveErrorReport {
            get {
                return ResourceManager.GetString("SaveErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存先 的本地化字符串。
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログをファイルに保存する 的本地化字符串。
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定されたフォルダは存在しません。 的本地化字符串。
        /// </summary>
        public static string SavePathDoesNotExist {
            get {
                return ResourceManager.GetString("SavePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存する 的本地化字符串。
        /// </summary>
        public static string SaveProxyScriptDialog {
            get {
                return ResourceManager.GetString("SaveProxyScriptDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信内容を保存する 的本地化字符串。
        /// </summary>
        public static string SaveReceivedData {
            get {
                return ResourceManager.GetString("SaveReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SWFファイルを保存します。 的本地化字符串。
        /// </summary>
        public static string SaveSWF {
            get {
                return ResourceManager.GetString("SaveSWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 シーン 的本地化字符串。
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショット 的本地化字符串。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これ統計データベースに送信する 的本地化字符串。
        /// </summary>
        public static string SendData {
            get {
                return ResourceManager.GetString("SendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名列のソート順： 的本地化字符串。
        /// </summary>
        public static string ShipNameSortMethod {
            get {
                return ResourceManager.GetString("ShipNameSortMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 あいうえお順 的本地化字符串。
        /// </summary>
        public static string ShipNameSortMethod_Alphabet {
            get {
                return ResourceManager.GetString("ShipNameSortMethod_Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 図鑑番号順 的本地化字符串。
        /// </summary>
        public static string ShipNameSortMethod_Number {
            get {
                return ResourceManager.GetString("ShipNameSortMethod_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘訓練 的本地化字符串。
        /// </summary>
        public static string ShipTraining {
            get {
                return ResourceManager.GetString("ShipTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HPバーを短縮し、スペースを節約します。 的本地化字符串。
        /// </summary>
        public static string ShortenHPHint {
            get {
                return ResourceManager.GetString("ShortenHPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 next. を表示する 的本地化字符串。
        /// </summary>
        public static string ShowNextXP {
            get {
                return ResourceManager.GetString("ShowNextXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下部のステータスバー(所属艦数など)を表示するかを指定します。
        ///わずかですが表示行数を増やすことができます。 的本地化字符串。
        /// </summary>
        public static string ShowStatusbarHint {
            get {
                return ResourceManager.GetString("ShowStatusbarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最前面に表示する 的本地化字符串。
        /// </summary>
        public static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サブフォント 的本地化字符串。
        /// </summary>
        public static string Subfont {
            get {
                return ResourceManager.GetString("Subfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破進撃 的本地化字符串。
        /// </summary>
        public static string TaihaAdvance {
            get {
                return ResourceManager.GetString("TaihaAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＊再起動後に反映されます。 的本地化字符串。
        /// </summary>
        public static string TakeEffectOnRestart {
            get {
                return ResourceManager.GetString("TakeEffectOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テキスト検索 的本地化字符串。
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドロップダウンメニューからフォントを探す代わりに、名前を書いて検索できるようにしました。
        ///この機能を有効にすると、ローカライゼーションが正しく機能しない場合があります。 的本地化字符串。
        /// </summary>
        public static string TextSearchToolTip {
            get {
                return ResourceManager.GetString("TextSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーマ 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーマ変更は再起動後にすべて反映されます。 的本地化字符串。
        /// </summary>
        public static string ThemeRestartWarning {
            get {
                return ResourceManager.GetString("ThemeRestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下 的本地化字符串。
        /// </summary>
        public static string ToolMenuAlignment_Bottom {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非表示 的本地化字符串。
        /// </summary>
        public static string ToolMenuAlignment_Invisible {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        public static string ToolMenuAlignment_Left {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        public static string ToolMenuAlignment_Right {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        public static string ToolMenuAlignment_Top {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツールメニューの配置： 的本地化字符串。
        /// </summary>
        public static string ToolMenuDockStyle {
            get {
                return ResourceManager.GetString("ToolMenuDockStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これに接続してから操作してください。 的本地化字符串。
        /// </summary>
        public static string TryAgainAfterConnect {
            get {
                return ResourceManager.GetString("TryAgainAfterConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バーの色を滑らかに変化させる 的本地化字符串。
        /// </summary>
        public static string UI_BarColorMorphing {
            get {
                return ResourceManager.GetString("UI_BarColorMorphing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遂行中のみ表示する 的本地化字符串。
        /// </summary>
        public static string UnderWayOnly {
            get {
                return ResourceManager.GetString("UnderWayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＊未実装です＊ 的本地化字符串。
        /// </summary>
        public static string Unimplemented {
            get {
                return ResourceManager.GetString("Unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシを利用でアップデートする 的本地化字符串。
        /// </summary>
        public static string UseGithubProxy {
            get {
                return ResourceManager.GetString("UseGithubProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムプロキシを利用 的本地化字符串。
        /// </summary>
        public static string UseSystemProxy {
            get {
                return ResourceManager.GetString("UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムのプロキシ設定を利用します。 的本地化字符串。
        /// </summary>
        public static string UseSystemProxyTooltip {
            get {
                return ResourceManager.GetString("UseSystemProxyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量： 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィークリー 的本地化字符串。
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ 的本地化字符串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザバージョンをレジストリに書き込みました。削除したい場合は「設定→サブウィンドウ→ブラウザ2→削除」を押してください。 的本地化字符串。
        /// </summary>
        public static string WriteRegistry {
            get {
                return ResourceManager.GetString("WriteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム倍率 的本地化字符串。
        /// </summary>
        public static string ZoomRate {
            get {
                return ResourceManager.GetString("ZoomRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ぴったり 的本地化字符串。
        /// </summary>
        public static string ZoomToFit {
            get {
                return ResourceManager.GetString("ZoomToFit", resourceCulture);
            }
        }
    }
}
