//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties.Window.Dialog {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogConfiguration() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Window.Dialog.DialogConfiguration", typeof(DialogConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 基地航空隊 的本地化字符串。
        /// </summary>
        public static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API リストを開く 的本地化字符串。
        /// </summary>
        public static string APIListBrowser {
            get {
                return ResourceManager.GetString("APIListBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アプリケーションID 的本地化字符串。
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※自動更新を有効にすると、
        ///　重くなる可能性があります 的本地化字符串。
        /// </summary>
        public static string AutoUpdateCouldIncreaseLoad {
            get {
                return ResourceManager.GetString("AutoUpdateCouldIncreaseLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ミュートを同期 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_SyncBrowserMute {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザのミュートと連動させるかを指定します。 的本地化字符串。
        /// </summary>
        public static string BGMPlayer_SyncBrowserMuteToolTip {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMuteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザ 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秘書のアイコンをゲーム画像として使用 的本地化字符串。
        /// </summary>
        public static string checkBoxUseSecretaryIconForRPC {
            get {
                return ResourceManager.GetString("checkBoxUseSecretaryIconForRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string checkBoxUseSecretaryIconForRPCToolTip {
            get {
                return ResourceManager.GetString("checkBoxUseSecretaryIconForRPCToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 時計表示： 的本地化字符串。
        /// </summary>
        public static string ClockMode {
            get {
                return ResourceManager.GetString("ClockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘 的本地化字符串。
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量一括設定の確認 的本地化字符串。
        /// </summary>
        public static string ConfirmSetting {
            get {
                return ResourceManager.GetString("ConfirmSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下流プロキシ(上級者向け)： 的本地化字符串。
        /// </summary>
        public static string Connection_DownstreamProxyLabel {
            get {
                return ResourceManager.GetString("Connection_DownstreamProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下流プロキシ設定を記述します。
        ///この設定は上記のポート設定より優先されます。
        ///空欄の場合は上記の設定をもとに自動設定されます。
        ///動作を理解できる方のみ利用してください。 的本地化字符串。
        /// </summary>
        public static string Connection_DownstreamProxyToolTip {
            get {
                return ResourceManager.GetString("Connection_DownstreamProxyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムプロキシとして登録 的本地化字符串。
        /// </summary>
        public static string Connection_RegisterAsSystemProxy {
            get {
                return ResourceManager.GetString("Connection_RegisterAsSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string Connection_SaveDataPathSearch {
            get {
                return ResourceManager.GetString("Connection_SaveDataPathSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信内容を保存する 的本地化字符串。
        /// </summary>
        public static string Connection_SaveReceivedData {
            get {
                return ResourceManager.GetString("Connection_SaveReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他のツール・ブラウザで利用しているポート番号を指定します。 的本地化字符串。
        /// </summary>
        public static string Connection_UpstreamProxyPortToolTip {
            get {
                return ResourceManager.GetString("Connection_UpstreamProxyPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムプロキシを利用 的本地化字符串。
        /// </summary>
        public static string Connection_UseSystemProxy {
            get {
                return ResourceManager.GetString("Connection_UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上流プロキシを利用する： 的本地化字符串。
        /// </summary>
        public static string Connection_UseUpstreamProxy {
            get {
                return ResourceManager.GetString("Connection_UseUpstreamProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他のプロキシを利用するツール・ブラウザと連携する際に利用します。 的本地化字符串。
        /// </summary>
        public static string Connection_UseUpstreamProxyToolTip {
            get {
                return ResourceManager.GetString("Connection_UseUpstreamProxyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord Rich Presenceで使用するアプリケーションID 的本地化字符串。
        /// </summary>
        public static string Control_ApplicationIDToolTip {
            get {
                return ResourceManager.GetString("Control_ApplicationIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 discordに表示するメッセージを選択できるようにします。メッセージに秘書の名前を入れるには{{secretary}}を使います。 的本地化字符串。
        /// </summary>
        public static string Control_DiscordRPCMessageToolTip {
            get {
                return ResourceManager.GetString("Control_DiscordRPCMessageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甲種勲章を表示 的本地化字符串。
        /// </summary>
        public static string Control_DiscordRPCShowFCM {
            get {
                return ResourceManager.GetString("Control_DiscordRPCShowFCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持っている甲種勲章の数を示すためにチェックします 的本地化字符串。
        /// </summary>
        public static string Control_DiscordRPCShowFCMToolTip {
            get {
                return ResourceManager.GetString("Control_DiscordRPCShowFCMToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord RPCの有効化 的本地化字符串。
        /// </summary>
        public static string Control_EnableDiscordRPC {
            get {
                return ResourceManager.GetString("Control_EnableDiscordRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord Rich Presenceの有効化 的本地化字符串。
        /// </summary>
        public static string Control_EnableDiscordRPCToolTip {
            get {
                return ResourceManager.GetString("Control_EnableDiscordRPCToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TsunDb送信を有効にする 的本地化字符串。
        /// </summary>
        public static string Control_EnableTsunDbSubmission {
            get {
                return ResourceManager.GetString("Control_EnableTsunDbSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強制アップデート 的本地化字符串。
        /// </summary>
        public static string Control_ForceUpdate {
            get {
                return ResourceManager.GetString("Control_ForceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T字有利 的本地化字符串。
        /// </summary>
        public static string Control_PowerEngagementForm_GreenT {
            get {
                return ResourceManager.GetString("Control_PowerEngagementForm_GreenT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反航戦 的本地化字符串。
        /// </summary>
        public static string Control_PowerEngagementForm_HeadOn {
            get {
                return ResourceManager.GetString("Control_PowerEngagementForm_HeadOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同航戦 的本地化字符串。
        /// </summary>
        public static string Control_PowerEngagementForm_Parallel {
            get {
                return ResourceManager.GetString("Control_PowerEngagementForm_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T字不利 的本地化字符串。
        /// </summary>
        public static string Control_PowerEngagementForm_RedT {
            get {
                return ResourceManager.GetString("Control_PowerEngagementForm_RedT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 威力（戦闘における攻撃力）を計算する際の、基準となる交戦形態を設定します。 的本地化字符串。
        /// </summary>
        public static string Control_PowerEngagementFormToolTip {
            get {
                return ResourceManager.GetString("Control_PowerEngagementFormToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失敗する遠征出撃時に警告する 的本地化字符串。
        /// </summary>
        public static string Control_ShowExpeditionAlertDialog {
            get {
                return ResourceManager.GetString("Control_ShowExpeditionAlertDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編成条件を満たさない艦隊が遠征に出発したときに、警告ダイアログを表示するかを指定します。 的本地化字符串。
        /// </summary>
        public static string Control_ShowExpeditionAlertDialogTooltip {
            get {
                return ResourceManager.GetString("Control_ShowExpeditionAlertDialogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃札がない艦娘が出撃したとき警告する 的本地化字符串。
        /// </summary>
        public static string Control_ShowSallyAreaAlertDialog {
            get {
                return ResourceManager.GetString("Control_ShowSallyAreaAlertDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃制限の札がついていない艦娘がイベント海域に出撃したとき、警告ダイアログを表示するかを指定します。
        ///得られる情報が不完全な関係上、誤判定を起こす可能性があります。ご了承ください。 的本地化字符串。
        /// </summary>
        public static string Control_ShowSallyAreaAlertDialogTooltip {
            get {
                return ResourceManager.GetString("Control_ShowSallyAreaAlertDialogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻訳の更新に使用するリポジトリを指定します 的本地化字符串。
        /// </summary>
        public static string Control_translationURLToolTip {
            get {
                return ResourceManager.GetString("Control_translationURLToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知・BGM音量にシステム設定を利用する 的本地化字符串。
        /// </summary>
        public static string Control_UseSystemVolume {
            get {
                return ResourceManager.GetString("Control_UseSystemVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知・BGM等の本体音量設定に、システム音量設定を利用するかを指定します。
        ///無効の場合は個別に音量を設定できますが、音量ミキサ等で調整できなくなります。
        ///有効の場合は音量ミキサ等で調整できますが、個別の音量設定は無視されます。 的本地化字符串。
        /// </summary>
        public static string Control_UseSystemVolumeToolTip {
            get {
                return ResourceManager.GetString("Control_UseSystemVolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デバッグ メニューを有効にする 的本地化字符串。
        /// </summary>
        public static string Debug_EnableDebugMenu {
            get {
                return ResourceManager.GetString("Debug_EnableDebugMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 メインウィンドウの[デバッグ]メニューを有効にします。
        ///デバッグ用の機能であるため、通常ユーザーの操作は推奨されません。
        ///使用時の動作は保証されないので、＊自己責任で＊使用してください。 的本地化字符串。
        /// </summary>
        public static string Debug_EnableDebugMenuToolTip {
            get {
                return ResourceManager.GetString("Debug_EnableDebugMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時にAPIリストをロード 的本地化字符串。
        /// </summary>
        public static string Debug_LoadAPIListOnLoad {
            get {
                return ResourceManager.GetString("Debug_LoadAPIListOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時に、下記テキストボックスで指定されるAPIリストを自動的に読み込みます。
        ///APIリストの書式や用法はオンラインヘルプを参照してください。 的本地化字符串。
        /// </summary>
        public static string Debug_LoadAPIListOnLoadToolTip {
            get {
                return ResourceManager.GetString("Debug_LoadAPIListOnLoadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        public static string DialogCaptionErrorTitle {
            get {
                return ResourceManager.GetString("DialogCaptionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord RPCメッセージ 的本地化字符串。
        /// </summary>
        public static string DiscordRPCMessage {
            get {
                return ResourceManager.GetString("DiscordRPCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編集 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備情報表示： 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelDisplay {
            get {
                return ResourceManager.GetString("EquipmentLevelDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 熟練度オーバーレイ 的本地化字符串。
        /// </summary>
        public static string EquipmentLevelVisibility_OverlayProficiency {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_OverlayProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトの保存に失敗しました。 的本地化字符串。
        /// </summary>
        public static string FailedToSavePac {
            get {
                return ResourceManager.GetString("FailedToSavePac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊 的本地化字符串。
        /// </summary>
        public static string Fleet {
            get {
                return ResourceManager.GetString("Fleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊状態表示： 的本地化字符串。
        /// </summary>
        public static string FleetStatus {
            get {
                return ResourceManager.GetString("FleetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名の表示幅の最大値を指定します。 的本地化字符串。
        /// </summary>
        public static string FormArsenal_MaxShipNameWidthToolTip {
            get {
                return ResourceManager.GetString("FormArsenal_MaxShipNameWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名を表示する 的本地化字符串。
        /// </summary>
        public static string FormArsenal_ShowShipName {
            get {
                return ResourceManager.GetString("FormArsenal_ShowShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 威力表示交戦形態： 的本地化字符串。
        /// </summary>
        public static string FormationModifier {
            get {
                return ResourceManager.GetString("FormationModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 イベント海域の基地のみ表示する 的本地化字符串。
        /// </summary>
        public static string FormBaseAirCorps_ShowEventMapOnly {
            get {
                return ResourceManager.GetString("FormBaseAirCorps_ShowEventMapOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合、イベント時に通常海域の基地航空隊を非表示にします。
        ///イベント期間外ではすべての航空隊が表示されます。 的本地化字符串。
        /// </summary>
        public static string FormBaseAirCorps_ShowEventMapOnlyToolTip {
            get {
                return ResourceManager.GetString("FormBaseAirCorps_ShowEventMapOnlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7番艦を同じ行に表示する 的本地化字符串。
        /// </summary>
        public static string FormBattle_Display7thAsSingleLine {
            get {
                return ResourceManager.GetString("FormBattle_Display7thAsSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遊撃部隊(7隻編成)での出撃時、7隻目の情報をどこに表示するか指定します。
        ///有効時は6隻目の下に、無効時は随伴艦隊1隻目と同じ位置に表示されます。
        ///無効にすると若干スペースを節約できます。 的本地化字符串。
        /// </summary>
        public static string FormBattle_Display7thAsSingleLineToolTip {
            get {
                return ResourceManager.GetString("FormBattle_Display7thAsSingleLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘終了まで隠す 的本地化字符串。
        /// </summary>
        public static string FormBattle_HideDuringBattle {
            get {
                return ResourceManager.GetString("FormBattle_HideDuringBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘中に戦闘予測画面を非表示にすることで、ネタバレを回避します。
        ///非表示状態でも、戦闘ウィンドウの右クリックメニューから一時的に表示することができます。 的本地化字符串。
        /// </summary>
        public static string FormBattle_HideDuringBattleToolTip {
            get {
                return ResourceManager.GetString("FormBattle_HideDuringBattleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HPバーを表示する 的本地化字符串。
        /// </summary>
        public static string FormBattle_ShowHPBar {
            get {
                return ResourceManager.GetString("FormBattle_ShowHPBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非表示にするとわずかではありますが縦幅を節約できます。 的本地化字符串。
        /// </summary>
        public static string FormBattle_ShowHPBarToolTip {
            get {
                return ResourceManager.GetString("FormBattle_ShowHPBarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HPバーに艦種略号を表示する 的本地化字符串。
        /// </summary>
        public static string FormBattle_ShowShipTypeInHPBar {
            get {
                return ResourceManager.GetString("FormBattle_ShowShipTypeInHPBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;HP:&quot; 表示の代わりに艦種略号を表示するかを指定します。
        ///長い略号の艦種は表示が被る可能性があります。 的本地化字符串。
        /// </summary>
        public static string FormBattle_ShowShipTypeInHPBarToolTip {
            get {
                return ResourceManager.GetString("FormBattle_ShowShipTypeInHPBarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再読み込み時に確認する 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ConfirmAtRefresh {
            get {
                return ResourceManager.GetString("FormBrowser_ConfirmAtRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合再読み込みするときに確認ダイアログを表示します。
        ///誤爆防止にご利用ください。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ConfirmAtRefreshToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_ConfirmAtRefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 カラープロファイルを sRGB に固定する * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ForceColorProfile {
            get {
                return ResourceManager.GetString("FormBrowser_ForceColorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザの色合いがおかしい場合、有効にすると解決するかもしれません。
        ///再起動すると反映されます。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ForceColorProfileToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_ForceColorProfileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ハードウェアアクセラレーションを有効にする * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_HardwareAccelerationEnabled {
            get {
                return ResourceManager.GetString("FormBrowser_HardwareAccelerationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描画に GPU を使用するかを指定します。
        ///有効にするとパフォーマンスが向上する可能性があります。
        ///録画・配信で画面が映らなくなる場合、無効にすると改善されるかもしれません。
        ///* この変更は再起動後に適用されます。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_HardwareAccelerationEnabledToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_HardwareAccelerationEnabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMMによるページ更新ダイアログを非表示にする 的本地化字符串。
        /// </summary>
        public static string FormBrowser_IsDMMreloadDialogDestroyable {
            get {
                return ResourceManager.GetString("FormBrowser_IsDMMreloadDialogDestroyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DMMによる「エラーが発生したため、ページ更新します。」の確認ダイアログを表示されないようにします。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_IsDMMreloadDialogDestroyableToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_IsDMMreloadDialogDestroyableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描画バッファを保持する * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_PreserveDrawingBuffer {
            get {
                return ResourceManager.GetString("FormBrowser_PreserveDrawingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描画系で問題があった場合有効にすると改善するかもしれません。
        ///無効にするとパフォーマンスが向上する可能性があります。
        ///* この変更は再起動後に適用されます。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_PreserveDrawingBufferToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_PreserveDrawingBufferToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザのエラーログを保存する * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_SavesBrowserLog {
            get {
                return ResourceManager.GetString("FormBrowser_SavesBrowserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合、BrowserLog.log にブラウザのエラーログを保存します。
        ///問題解決に役立つかもしれませんが、書き込みによって動作が重くなる可能性があります。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_SavesBrowserLogTooltip {
            get {
                return ResourceManager.GetString("FormBrowser_SavesBrowserLogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter の画像圧縮を回避する 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ScreenShotFormat_AvoidTwitterDeterioration {
            get {
                return ResourceManager.GetString("FormBrowser_ScreenShotFormat_AvoidTwitterDeterioration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter に PNG 形式の画像をアップロードすると、自動的に JPEG 形式に変換され画質が劣化します。
        ///それを回避するための情報を埋め込むかを指定します。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ScreenShotFormat_AvoidTwitterDeteriorationToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_ScreenShotFormat_AvoidTwitterDeteriorationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 両方保存 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ScreenShotSaveMode_Both {
            get {
                return ResourceManager.GetString("FormBrowser_ScreenShotSaveMode_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クリップボードにコピー 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ScreenShotSaveMode_ToClipboard {
            get {
                return ResourceManager.GetString("FormBrowser_ScreenShotSaveMode_ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイルに保存 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ScreenShotSaveMode_ToFile {
            get {
                return ResourceManager.GetString("FormBrowser_ScreenShotSaveMode_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 コンテキストメニューを表示する 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ShowContextMenu {
            get {
                return ResourceManager.GetString("FormBrowser_ShowContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザ上で右クリックすると、コンテキストメニューが表示されます。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_ShowContextMenuToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_ShowContextMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ガジェット・リダイレクトの使用 * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_UseGadgetRedirect {
            get {
                return ResourceManager.GetString("FormBrowser_UseGadgetRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外国人ブロックを回避するために、ガジェットのapiコールをリダイレクトします。
        ///日本にお住まいの方や、日本のVPNをご利用の方は、このオプションを無効にしておくことができます。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_UseGadgetRedirectToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_UseGadgetRedirectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vulkanの回避策 * 的本地化字符串。
        /// </summary>
        public static string FormBrowser_UseVulkanWorkaround {
            get {
                return ResourceManager.GetString("FormBrowser_UseVulkanWorkaround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 古いハードウェアで高いCPU負荷を引き起こす可能性のあるvulkanソフトウェアレンダリング実装に必要なWebView2ファイルを削除しました。 的本地化字符串。
        /// </summary>
        public static string FormBrowser_UseVulkanWorkaroundToolTip {
            get {
                return ResourceManager.GetString("FormBrowser_UseVulkanWorkaroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 熟練度を無視 的本地化字符串。
        /// </summary>
        public static string FormFleet_AirSuperiorityMethod_Disabled {
            get {
                return ResourceManager.GetString("FormFleet_AirSuperiorityMethod_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 熟練度を含む 的本地化字符串。
        /// </summary>
        public static string FormFleet_AirSuperiorityMethod_Enabled {
            get {
                return ResourceManager.GetString("FormFleet_AirSuperiorityMethod_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃海域で艦名を色分けする 的本地化字符串。
        /// </summary>
        public static string FormFleet_AppliesSallyAreaColor {
            get {
                return ResourceManager.GetString("FormFleet_AppliesSallyAreaColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃海域によって艦名の背景色を設定します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_AppliesSallyAreaColorToolTip {
            get {
                return ResourceManager.GetString("FormFleet_AppliesSallyAreaColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征・入渠等の完了時に、ラベルを点滅させるかを指定します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_BlinkAtCompletionToolTip {
            get {
                return ResourceManager.GetString("FormFleet_BlinkAtCompletionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破時に点滅させる 的本地化字符串。
        /// </summary>
        public static string FormFleet_BlinkAtDamaged {
            get {
                return ResourceManager.GetString("FormFleet_BlinkAtDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 母港において、大破艦が存在するときに点滅表示させるかを指定します。
        ///出撃時は常に点滅が有効です。 的本地化字符串。
        /// </summary>
        public static string FormFleet_BlinkAtDamagedToolTip {
            get {
                return ResourceManager.GetString("FormFleet_BlinkAtDamagedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征艦隊未出撃時に強調表示 的本地化字符串。
        /// </summary>
        public static string FormFleet_EmphasizesSubFleetInPort {
            get {
                return ResourceManager.GetString("FormFleet_EmphasizesSubFleetInPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第2~4艦隊が母港に存在するとき、色付きで表示するようにします。 的本地化字符串。
        /// </summary>
        public static string FormFleet_EmphasizesSubFleetInPortToolTip {
            get {
                return ResourceManager.GetString("FormFleet_EmphasizesSubFleetInPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備の改修レベルや艦載機熟練度の表示を指定します。
        ///「非表示」の場合は表示しません。
        ///「～優先」の場合、どちらもLv.1以上の時にそれぞれを優先して表示します。
        ///「両方表示」の場合は常にどちらも表示します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_EquipmentLevelVisibilityToolTip {
            get {
                return ResourceManager.GetString("FormFleet_EquipmentLevelVisibilityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名の横幅固定が有効なときのサイズを指定します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_FixedShipNameWidthToolTip {
            get {
                return ResourceManager.GetString("FormFleet_FixedShipNameWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名の横幅を固定する 的本地化字符串。
        /// </summary>
        public static string FormFleet_FixShipNameWidth {
            get {
                return ResourceManager.GetString("FormFleet_FixShipNameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名表示部の幅を固定し、スペースを節約します。
        ///代わりに長い名前を持つ艦娘は見切れます。 的本地化字符串。
        /// </summary>
        public static string FormFleet_FixShipNameWidthToolTip {
            get {
                return ResourceManager.GetString("FormFleet_FixShipNameWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全て短縮表示 的本地化字符串。
        /// </summary>
        public static string FormFleet_FleetStateDisplayMode_CollapseAll {
            get {
                return ResourceManager.GetString("FormFleet_FleetStateDisplayMode_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 複数表示時に短縮 的本地化字符串。
        /// </summary>
        public static string FormFleet_FleetStateDisplayMode_CollapseMultiple {
            get {
                return ResourceManager.GetString("FormFleet_FleetStateDisplayMode_CollapseMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全て通常表示 的本地化字符串。
        /// </summary>
        public static string FormFleet_FleetStateDisplayMode_ExpandAll {
            get {
                return ResourceManager.GetString("FormFleet_FleetStateDisplayMode_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1つだけ表示 的本地化字符串。
        /// </summary>
        public static string FormFleet_FleetStateDisplayMode_SingleStatus {
            get {
                return ResourceManager.GetString("FormFleet_FleetStateDisplayMode_SingleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクロールバーを表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_IsScrollable {
            get {
                return ResourceManager.GetString("FormFleet_IsScrollable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示エリアがはみ出した場合にスクロールバーを表示するかを指定します。
        ///収まりきった場合は表示しません。 的本地化字符串。
        /// </summary>
        public static string FormFleet_IsScrollableToolTip {
            get {
                return ResourceManager.GetString("FormFleet_IsScrollableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泊地修理によるHP回復を反映する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ReflectAnchorageRepairHealing {
            get {
                return ResourceManager.GetString("FormFleet_ReflectAnchorageRepairHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な場合、泊地修理開始から20分以上経過するとHPバーに回復量が表示されるようになります。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ReflectAnchorageRepairHealingToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ReflectAnchorageRepairHealingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HPバーを短縮する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShortenHPBar {
            get {
                return ResourceManager.GetString("FormFleet_ShortenHPBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦載機数を表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAircraft {
            get {
                return ResourceManager.GetString("FormFleet_ShowAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦載機熟練度を数字で表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAircraftLevelByNumber {
            get {
                return ResourceManager.GetString("FormFleet_ShowAircraftLevelByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦載機熟練度を記号（|, || など）ではなく、数字（1, 2 など）で表示するかを指定します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAircraftLevelByNumberToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ShowAircraftLevelByNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空戦力を範囲表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAirSuperiorityRange {
            get {
                return ResourceManager.GetString("FormFleet_ShowAirSuperiorityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空戦力の範囲を「内部熟練度最小～最大」として範囲表示するかを指定します。
        ///通常、制空戦力は最低の内部熟練度を持つとして計算されます。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAirSuperiorityRangeToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ShowAirSuperiorityRangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泊地修理タイマを表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAnchorageRepairingTimer {
            get {
                return ResourceManager.GetString("FormFleet_ShowAnchorageRepairingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊一覧の泊地修理タイマを表示するかを指定します。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowAnchorageRepairingTimerToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ShowAnchorageRepairingTimerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労度アイコンを表示する 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowConditionIcon {
            get {
                return ResourceManager.GetString("FormFleet_ShowConditionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労度のアイコンを表示するかを指定します。
        ///表示しない場合、背景色で区別されます。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowConditionIconToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ShowConditionIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「次のレベルまでに必要な経験値」を表示するかを指定します。
        ///省略した場合スペースを節約できます。 的本地化字符串。
        /// </summary>
        public static string FormFleet_ShowNextExpToolTip {
            get {
                return ResourceManager.GetString("FormFleet_ShowNextExpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動更新する 的本地化字符串。
        /// </summary>
        public static string FormJson_AutoUpdate {
            get {
                return ResourceManager.GetString("FormJson_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動更新時に読み込む API を選択するフィルタです。
        ///正規表現も利用可能です。 的本地化字符串。
        /// </summary>
        public static string FormJson_AutoUpdateFilterToolTip {
            get {
                return ResourceManager.GetString("FormJson_AutoUpdateFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API の送受信時に、自動で表示を更新するかを指定します。
        ///多少重くなる可能性があります。 的本地化字符串。
        /// </summary>
        public static string FormJson_AutoUpdateToolTip {
            get {
                return ResourceManager.GetString("FormJson_AutoUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Treeも更新する 的本地化字符串。
        /// </summary>
        public static string FormJson_UpdatesTree {
            get {
                return ResourceManager.GetString("FormJson_UpdatesTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API の送受信時に、自動で Tree 表示を更新するかを指定します。
        ///上の「自動更新する」が有効の時のみ更新されます。
        ///多少重くなる可能性があります。 的本地化字符串。
        /// </summary>
        public static string FormJson_UpdatesTreeToolTip {
            get {
                return ResourceManager.GetString("FormJson_UpdatesTreeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ステータスバーを表示する 的本地化字符串。
        /// </summary>
        public static string FormShipGroup_ShowStatusBar {
            get {
                return ResourceManager.GetString("FormShipGroup_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同じ艦娘に対して訓練プランを追加できるようにする 的本地化字符串。
        /// </summary>
        public static string FormShipTraining_AllowMultiplePlanPerShip {
            get {
                return ResourceManager.GetString("FormShipTraining_AllowMultiplePlanPerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 チェックを外すと、新しい艦娘の訓練プランを追加する際に、訓練プランのない艦娘だけが表示されるように艦娘リストがフィルタリングされます。
        ///チェックした場合、フィルターは適用されません。 的本地化字符串。
        /// </summary>
        public static string FormShipTraining_AllowMultiplePlanPerShipToolTip {
            get {
                return ResourceManager.GetString("FormShipTraining_AllowMultiplePlanPerShipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司令部 的本地化字符串。
        /// </summary>
        public static string HQ {
            get {
                return ResourceManager.GetString("HQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英語 的本地化字符串。
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡体中文 的本地化字符串。
        /// </summary>
        public static string Language_SimplifiedChinese {
            get {
                return ResourceManager.GetString("Language_SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上記「レイアウトをロックする」が有効な時でも、
        ///フロートウィンドウ(本体とは分離したウィンドウ)を閉じられるようにするかを指定します。
        ///よくウィンドウを一時的に開く方は有効にすると便利です。 的本地化字符串。
        /// </summary>
        public static string Life_CanCloseFloatWindowInLockToolTip {
            get {
                return ResourceManager.GetString("Life_CanCloseFloatWindowInLockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートを確認する 的本地化字符串。
        /// </summary>
        public static string Life_CheckUpdateInformation {
            get {
                return ResourceManager.GetString("Life_CheckUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演習更新まで 的本地化字符串。
        /// </summary>
        public static string Life_ClockFormat_PvpReset {
            get {
                return ResourceManager.GetString("Life_ClockFormat_PvpReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務更新まで 的本地化字符串。
        /// </summary>
        public static string Life_ClockFormat_QuestReset {
            get {
                return ResourceManager.GetString("Life_ClockFormat_QuestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在時刻 的本地化字符串。
        /// </summary>
        public static string Life_ClockFormat_ServerTime {
            get {
                return ResourceManager.GetString("Life_ClockFormat_ServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終了時に確認する 的本地化字符串。
        /// </summary>
        public static string Life_ConfirmOnClosing {
            get {
                return ResourceManager.GetString("Life_ConfirmOnClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウトをロックする 的本地化字符串。
        /// </summary>
        public static string Life_LockLayout {
            get {
                return ResourceManager.GetString("Life_LockLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サイズやレイアウトの変更を防止するかを指定します。 的本地化字符串。
        /// </summary>
        public static string Life_LockLayoutToolTip {
            get {
                return ResourceManager.GetString("Life_LockLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ステータスバーを表示する 的本地化字符串。
        /// </summary>
        public static string Life_ShowStatusBar {
            get {
                return ResourceManager.GetString("Life_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最前面に表示する 的本地化字符串。
        /// </summary>
        public static string Life_TopMost {
            get {
                return ResourceManager.GetString("Life_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小さい値では詳細なログを、大きな値では重要なログのみを表示します。
        ///1: デバッグレベル
        ///2: 通常(推奨)
        ///3: エラーのみ 的本地化字符串。
        /// </summary>
        public static string Log_LogLevelToolTip {
            get {
                return ResourceManager.GetString("Log_LogLevelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プレイ時間 的本地化字符串。
        /// </summary>
        public static string Log_PlayTime {
            get {
                return ResourceManager.GetString("Log_PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘ログを保存する 的本地化字符串。
        /// </summary>
        public static string Log_SaveBattleLog {
            get {
                return ResourceManager.GetString("Log_SaveBattleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘ログを保存するかを指定します。
        ///戦闘ログは BattleLog フォルダに保存されます。 的本地化字符串。
        /// </summary>
        public static string Log_SaveBattleLogToolTip {
            get {
                return ResourceManager.GetString("Log_SaveBattleLogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログを即時書き込みする 的本地化字符串。
        /// </summary>
        public static string Log_SaveLogImmediately {
            get {
                return ResourceManager.GetString("Log_SaveLogImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログ追加と同時にログファイルに書き込むかを指定します。
        ///無効の場合はプログラム終了時にまとめて書き込みます。
        ///有効な場合、強制終了等の問題が発生してもログを残せますが、多少処理が重くなる可能性があります。
        ///なお、「ログをファイルに保存する」無効時には本指定は無効になります。 的本地化字符串。
        /// </summary>
        public static string Log_SaveLogImmediatelyToolTip {
            get {
                return ResourceManager.GetString("Log_SaveLogImmediatelyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ネタバレを許可する 的本地化字符串。
        /// </summary>
        public static string Log_ShowSpoiler {
            get {
                return ResourceManager.GetString("Log_ShowSpoiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開発したアイテム名やドロップ艦名などのログを記録するかを指定します。
        ///先にわかってしまうことが気になる方は無効にしてください。 的本地化字符串。
        /// </summary>
        public static string Log_ShowSpoilerToolTip {
            get {
                return ResourceManager.GetString("Log_ShowSpoilerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レコードの自動保存： 的本地化字符串。
        /// </summary>
        public static string LogFrequency {
            get {
                return ResourceManager.GetString("LogFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名の最大横幅： 的本地化字符串。
        /// </summary>
        public static string NameWidth {
            get {
                return ResourceManager.GetString("NameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * ブラウザに対する通信設定は、再起動すると反映されます 的本地化字符串。
        /// </summary>
        public static string NetworkSettingsNote {
            get {
                return ResourceManager.GetString("NetworkSettingsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基地航空隊通知の設定... 的本地化字符串。
        /// </summary>
        public static string Notification_BaseAirCorps {
            get {
                return ResourceManager.GetString("Notification_BaseAirCorps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バトル終了通知 的本地化字符串。
        /// </summary>
        public static string Notification_BattleEnd {
            get {
                return ResourceManager.GetString("Notification_BattleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改造レベル 的本地化字符串。
        /// </summary>
        public static string Notification_RemodelLevel {
            get {
                return ResourceManager.GetString("Notification_RemodelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべての通知をミュート 的本地化字符串。
        /// </summary>
        public static string Notification_Silencio {
            get {
                return ResourceManager.GetString("Notification_Silencio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべての通知を非表示にし、通知音の発声も停止します。
        ///
        ///「シレンシオ！黙れ！」 的本地化字符串。
        /// </summary>
        public static string Notification_SilencioToolTip {
            get {
                return ResourceManager.GetString("Notification_SilencioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由アイテム表示欄： 的本地化字符串。
        /// </summary>
        public static string OtherItem {
            get {
                return ResourceManager.GetString("OtherItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存方法： 的本地化字符串。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作成完了 的本地化字符串。
        /// </summary>
        public static string PacSavedTitle {
            get {
                return ResourceManager.GetString("PacSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべてのBGMに対して音量 {0} を適用します。
        ///よろしいですか？ 的本地化字符串。
        /// </summary>
        public static string PlayerVolumeWillBeSet {
            get {
                return ResourceManager.GetString("PlayerVolumeWillBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これに接続してから操作してください。 的本地化字符串。
        /// </summary>
        public static string PleaseStartKancolle {
            get {
                return ResourceManager.GetString("PleaseStartKancolle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポートと上流プロキシポートの値は異なる必要があります 的本地化字符串。
        /// </summary>
        public static string PortAndUpstreamPortMustBeDifferent {
            get {
                return ResourceManager.GetString("PortAndUpstreamPortMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即時 的本地化字符串。
        /// </summary>
        public static string ProgressAutoSaving_Immediately {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存し、設定用URLをクリップボードにコピーしました。
        ///所定の位置に貼り付けてください。 的本地化字符串。
        /// </summary>
        public static string ProxyAutoConfigSaved {
            get {
                return ResourceManager.GetString("ProxyAutoConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * マークのある設定は、再起動すると反映されます 的本地化字符串。
        /// </summary>
        public static string RestartNotice {
            get {
                return ResourceManager.GetString("RestartNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定されたフォルダは存在しません。 的本地化字符串。
        /// </summary>
        public static string SaveDataPathDoesNotExist {
            get {
                return ResourceManager.GetString("SaveDataPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存する 的本地化字符串。
        /// </summary>
        public static string SavePacFileAs {
            get {
                return ResourceManager.GetString("SavePacFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショット 的本地化字符串。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 母港ソート順 的本地化字符串。
        /// </summary>
        public static string ShipNameSortMethod_GameSort {
            get {
                return ResourceManager.GetString("ShipNameSortMethod_GameSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示/非表示設定： 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silence while fullscreen 的本地化字符串。
        /// </summary>
        public static string silenceFullscreen {
            get {
                return ResourceManager.GetString("silenceFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 動作 的本地化字符串。
        /// </summary>
        public static string TabPage4 {
            get {
                return ResourceManager.GetString("TabPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーマ： 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 カスタム 的本地化字符串。
        /// </summary>
        public static string Theme_Custom {
            get {
                return ResourceManager.GetString("Theme_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ダーク 的本地化字符串。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ライト 的本地化字符串。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定したカラーテーマを使用します。
        ///変更は再起動後に反映されます。
        ///カスタムオプションは、Settings\ColorScheme.jsonのカラー値を使用します。 的本地化字符串。
        /// </summary>
        public static string ThemeToolTip {
            get {
                return ResourceManager.GetString("ThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻訳URL 的本地化字符串。
        /// </summary>
        public static string TranslationURL {
            get {
                return ResourceManager.GetString("TranslationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HP・資源等のバーの色を、艦これUIと同様に滑らかに変化させるか指定します。 的本地化字符串。
        /// </summary>
        public static string UI_BarColorMorphingToolTip {
            get {
                return ResourceManager.GetString("UI_BarColorMorphingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他の翻訳を無効にする 的本地化字符串。
        /// </summary>
        public static string UI_DisableOtherTranslations {
            get {
                return ResourceManager.GetString("UI_DisableOtherTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征、出撃マップ、クエスト 的本地化字符串。
        /// </summary>
        public static string UI_DisableOtherTranslationsToolTip {
            get {
                return ResourceManager.GetString("UI_DisableOtherTranslationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フォントの高さを固定する 的本地化字符串。
        /// </summary>
        public static string UI_IsLayoutFixed {
            get {
                return ResourceManager.GetString("UI_IsLayoutFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有効な時、どんなフォントでも概ね各UIの列の高さが同じになります(ver. 2.6.2 以前と同様)。
        ///無効な時、フォントによって列の高さが変わります(有効な時より大きくなる場合があります)。
        ///無効にした場合、動作が若干重くなる可能性があります。 的本地化字符串。
        /// </summary>
        public static string UI_IsLayoutFixedToolTip {
            get {
                return ResourceManager.GetString("UI_IsLayoutFixedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備名翻訳を無効にする 的本地化字符串。
        /// </summary>
        public static string UI_JapaneseEquipmentNames {
            get {
                return ResourceManager.GetString("UI_JapaneseEquipmentNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備種翻訳を無効にする 的本地化字符串。
        /// </summary>
        public static string UI_JapaneseEquipmentTypes {
            get {
                return ResourceManager.GetString("UI_JapaneseEquipmentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名翻訳を無効にする 的本地化字符串。
        /// </summary>
        public static string UI_JapaneseShipNames {
            get {
                return ResourceManager.GetString("UI_JapaneseShipNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦種翻訳を無効にする 的本地化字符串。
        /// </summary>
        public static string UI_JapaneseShipTypes {
            get {
                return ResourceManager.GetString("UI_JapaneseShipTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語： 的本地化字符串。
        /// </summary>
        public static string UI_LanguageLabel {
            get {
                return ResourceManager.GetString("UI_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描画プレビューです。
        ///下のバーから値を調整できます。 的本地化字符串。
        /// </summary>
        public static string UI_RenderingTestToolTip {
            get {
                return ResourceManager.GetString("UI_RenderingTestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーマや言語を変更した後は、七四式を再起動してください。 的本地化字符串。
        /// </summary>
        public static string UI_RestartHint {
            get {
                return ResourceManager.GetString("UI_RestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動更新フィルタ： 的本地化字符串。
        /// </summary>
        public static string UpdateFilter {
            get {
                return ResourceManager.GetString("UpdateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上流プロキシのアドレスを指定します。
        ///既定値は 127.0.0.1 です。 的本地化字符串。
        /// </summary>
        public static string UpstreamProxyToolTip {
            get {
                return ResourceManager.GetString("UpstreamProxyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 マスの指定にアルファベットを使用 的本地化字符串。
        /// </summary>
        public static string UseLetterForNodes {
            get {
                return ResourceManager.GetString("UseLetterForNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サブウィンドウ 的本地化字符串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム倍率： 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
